---
title: "Erste Analyse"
author: "Fabian Fiedler"
date: "1/18/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, comment=NULL)
```


```{r}
library(tidyverse)
library(magrittr)
library(readxl)
library(knitr)
```

```{r}
studdat <- read_excel(file.path("Daten","StudierendenDaten",
                                "StudDat.xlsx"))
```

```{r}
names(studdat)
```

```{r}
(studdat %>% names())[1:3]
```

```{r}
studdat %>%
  select(Gender, Size, Weight) %>%
  drop_na() %>%
  group_by(Gender) %>%
  summarise(mittlere_Größe=mean(Size), mittleres_Gewicht=mean(Weight)) %>%
  kable()
```

```{r}
studdat %>%
  select(Gender, Size, Weight) %>%
  drop_na()%>%
  ggplot(aes(x=Size, y=Weight, color=Gender)) + 
  geom_point() +
  geom_smooth(method="lm", se=FALSE) +
  scale_x_continuous("Größe") + 
  scale_y_continuous("Gewicht")
```

```{r}
studdat %>%
  select(Gender, SizeFather, SizeMother) %>%
  drop_na()%>%
  ggplot(aes(x=SizeFather, y=SizeMother)) +
  geom_jitter() + 
  geom_abline(xintercept=0, slope=1, color="orange") + 
  geom_smooth(method="lm", se=FALSE) + 
  geom_smooth(se=FALSE, color="red")
#alles was unter linie liegt = väter größer als mutter
#alles drüber ist mutter größer als vater
```
```
Erlärung für Überliegende Abbildung:

Orange Gerade:
Punkt auf der Gerade = Mann & Frau Gleich groß
Alles was unter linie liegt = Vater größer als Mutter
Alles drüber ist = Mutter größer als Vater

Blaue Gerade = Regressionsgerade
```

```{r}
studdat %>%
  select(Gender, Size, Weight) %>%
  drop_na()%>%
  ggplot(aes(x=Size, y=Weight, color=Gender)) +
  geom_boxplot()
```

```{r}
studdat %>%
  select(Gender, Size, Weight) %>%
  drop_na()%>%
  ggplot(aes(x=Size, fill=Gender)) +
  geom_density(alpha=0.8)
```

```{r}
studdat %>%
  select(Gender, Size, Weight) %>%
  drop_na()%>%
  ggplot(aes(x=Size, y=Weight, color=Gender)) + 
  geom_point(alpha=0.2, size=5) +
  geom_smooth(method="lm", se=FALSE) +
  scale_x_continuous("Größe") + 
  scale_y_continuous("Gewicht")
```

```{r}
studdat %>%
  select(Gender,Smoker, SmokeFather, SmokeMother) %>%
  drop_na()%>%
  group_by(Smoker, SmokeFather) %>%
  tally() -> table_father
#  summarise(n=n()) #entspricht tally() 
```

```{r}
table_father %>%
  select(SmokeFather, Smoker, n) %>%
  pivot_wider(names_from = Smoker, values_from=n) %>%
  rename(Smoker_yes=yes, Smoker_no=no)
```

```{r}
table_father %>%
  select(SmokeFather, Smoker, n) %>%
  pivot_wider(names_from = Smoker, values_from=n) %>%
  rename(Smoker_yes=yes, Smoker_no=no) %>%
  mutate(Smoker=Smoker_yes+Smoker_no) %>%
  mutate(Smoker_no=Smoker_no/Smoker, Smoker_yes=Smoker_yes/Smoker) %>%
  select(-Smoker) %>%
  kable(digits=3)
```